package autoloader

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// BinTargetType classifies a bin target file.
type BinTargetType int

const (
	BinPHPNoShebang BinTargetType = iota
	BinPHPWithShebang
	BinNonPHP
)

var phpDetectRegex = regexp.MustCompile(`(?s)^(#!.*?\r?\n)?[\r\n\t ]*<\?php`)

// DetectBinTarget reads the first 500 bytes and classifies the file.
func DetectBinTarget(path string) (BinTargetType, error) {
	f, err := os.Open(path)
	if err != nil {
		return BinNonPHP, fmt.Errorf("detect bin target: %w", err)
	}
	defer f.Close()

	buf := make([]byte, 500)
	n, _ := f.Read(buf)
	content := buf[:n]

	// Strip UTF-8 BOM if present
	if len(content) >= 3 && content[0] == 0xEF && content[1] == 0xBB && content[2] == 0xBF {
		content = content[3:]
	}

	if !phpDetectRegex.Match(content) {
		return BinNonPHP, nil
	}

	// Check if it has a shebang
	if len(content) >= 2 && content[0] == '#' && content[1] == '!' {
		return BinPHPWithShebang, nil
	}
	return BinPHPNoShebang, nil
}


// BuildIncludePath returns the PHP include path string for a bin proxy.
func BuildIncludePath(packageName, binEntry string) string {
	return fmt.Sprintf("__DIR__ . '/..'.'/%s/%s'", packageName, binEntry)
}

// GeneratePHPProxyNoShebang generates the proxy for PHP targets without a shebang.
func GeneratePHPProxyNoShebang(packageName, binEntry string) string {
	includePath := BuildIncludePath(packageName, binEntry)
	return fmt.Sprintf(`#!/usr/bin/env php
<?php

/**
 * Proxy PHP file generated by Allegro
 *
 * @generated
 */

namespace Composer;

$GLOBALS['_composer_bin_dir'] = __DIR__;
$GLOBALS['_composer_autoload_path'] = __DIR__ . '/..'.'/autoload.php';

return include %s;
`, includePath)
}

// GeneratePHPProxyWithShebang generates the proxy for PHP targets with a shebang.
func GeneratePHPProxyWithShebang(packageName, binEntry string) string {
	includePath := BuildIncludePath(packageName, binEntry)
	return fmt.Sprintf(`#!/usr/bin/env php
<?php

/**
 * Proxy PHP file generated by Allegro
 *
 * @generated
 */

namespace Composer;

if (PHP_VERSION_ID < 80000) {
    if (!class_exists('Composer\BinProxyWrapper')) {
        /**
         * @internal
         */
        final class BinProxyWrapper
        {
            private $handle;
            private $position = 0;
            private $content;

            public function stream_open($path, $mode, $options, &$opened_path)
            {
                $this->content = file_get_contents(substr($path, 17)); // 17 = strlen('phpvfscomposer://')
                if ($this->content === false) {
                    return false;
                }
                // Strip shebang line
                if (strpos($this->content, '#!') === 0) {
                    $newlinePos = strpos($this->content, "\n");
                    if ($newlinePos !== false) {
                        $this->content = substr($this->content, $newlinePos + 1);
                    }
                }
                return true;
            }

            public function stream_read($count)
            {
                $ret = substr($this->content, $this->position, $count);
                $this->position += strlen($ret);
                return $ret;
            }

            public function stream_tell()
            {
                return $this->position;
            }

            public function stream_eof()
            {
                return $this->position >= strlen($this->content);
            }

            public function stream_seek($offset, $whence)
            {
                switch ($whence) {
                    case SEEK_SET:
                        $this->position = $offset;
                        return true;
                    case SEEK_CUR:
                        $this->position += $offset;
                        return true;
                    case SEEK_END:
                        $this->position = strlen($this->content) + $offset;
                        return true;
                    default:
                        return false;
                }
            }

            public function stream_stat()
            {
                return array();
            }
        }
    }

    if (
        (function_exists('stream_get_wrappers') && in_array('phpvfscomposer', stream_get_wrappers(), true))
        || (function_exists('stream_wrapper_register') && stream_wrapper_register('phpvfscomposer', 'Composer\BinProxyWrapper'))
    ) {
        return include 'phpvfscomposer://' . %s;
    }
}

$GLOBALS['_composer_bin_dir'] = __DIR__;
$GLOBALS['_composer_autoload_path'] = __DIR__ . '/..'.'/autoload.php';

return include %s;
`, includePath, includePath)
}

// GenerateShellProxy generates the POSIX shell proxy for non-PHP targets.
func GenerateShellProxy(packageName, binEntry string) string {
	return fmt.Sprintf(`#!/bin/sh

# Proxy shell script generated by Allegro
# @generated

dir=$(cd "$(dirname "$0")" && pwd)
export COMPOSER_RUNTIME_BIN_DIR="$dir"

"$dir"/../%s/%s "$@"
`, packageName, binEntry)
}

// BinBasename extracts the filename from a bin entry path.
func BinBasename(binEntry string) string {
	parts := strings.Split(binEntry, "/")
	return parts[len(parts)-1]
}
